"use client"

import { useParams } from "next/navigation"
import { BreakTimesheetTable } from "@/components/break-timesheet-table"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Calendar, Clock, Users } from "lucide-react"

export default function SharedTimesheetPage() {
  const params = useParams()
  const token = params.token as string

  // In a real app, you would decode the token and fetch the actual data
  // For demo purposes, we'll show sample data
  const sharedData = {
    companyName: "Acme Corporation",
    department: "Customer Service",
    dateRange: "December 2024",
    generatedBy: "Sarah Johnson",
    generatedAt: new Date().toLocaleDateString(),
  }

  return (
    <div className="min-h-screen bg-background p-4">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Header */}
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-bold">Shared Break Timesheet</h1>
          <p className="text-muted-foreground">View-only access to break schedule and compliance data</p>
        </div>

        {/* Shared Info Card */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Users className="h-5 w-5" />
              Timesheet Information
            </CardTitle>
            <CardDescription>Details about this shared timesheet</CardDescription>
          </CardHeader>
          <CardContent className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="space-y-2">
              <p className="text-sm font-medium text-muted-foreground">Company</p>
              <p className="font-semibold">{sharedData.companyName}</p>
            </div>
            <div className="space-y-2">
              <p className="text-sm font-medium text-muted-foreground">Department</p>
              <p className="font-semibold">{sharedData.department}</p>
            </div>
            <div className="space-y-2">
              <p className="text-sm font-medium text-muted-foreground">Period</p>
              <div className="flex items-center gap-2">
                <Calendar className="h-4 w-4" />
                <span className="font-semibold">{sharedData.dateRange}</span>
              </div>
            </div>
            <div className="space-y-2">
              <p className="text-sm font-medium text-muted-foreground">Generated</p>
              <div className="space-y-1">
                <p className="font-semibold">{sharedData.generatedBy}</p>
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Clock className="h-3 w-3" />
                  <span>{sharedData.generatedAt}</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Access Badge */}
        <div className="flex justify-center">
          <Badge variant="secondary" className="px-4 py-2">
            <span className="mr-2">🔗</span>
            Shared Access Token: {token.slice(0, 8)}...
          </Badge>
        </div>

        {/* Timesheet Table */}
        <BreakTimesheetTable readOnly={true} />

        {/* Footer */}
        <div className="text-center text-sm text-muted-foreground border-t pt-4">
          <p>This is a read-only view of the break timesheet.</p>
          <p>Generated by Employee Break Management System</p>
        </div>
      </div>
    </div>
  )
}
